# Generated by Django 4.2.4 on 2023-09-01 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='order',
            name='work_types',
        ),
        migrations.AddField(
            model_name='order',
            name='car_class',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='car_wash.employee'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='vacuum',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='wash_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
        migrations.DeleteModel(
            name='WorkType',
        ),
        migrations.AddField(
            model_name='order',
            name='additional_services',
            field=models.ManyToManyField(to='car_wash.additionalservice'),
        ),
    ]
