# Generated by Django 4.2.4 on 2023-09-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0004_alter_additionalservice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalservice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
